// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as CategoryIdRoute from "@/app/[categoryId]/page.info";
import * as CategoryIdStateStateIdRoute from "@/app/[categoryId]/state/[stateId]/page.info";
import * as CategoryIdStateStateIdHikingIdRoute from "@/app/[categoryId]/state/[stateId]/[hikingId]/page.info";
import * as AdminRoute from "@/app/admin/page.info";
import * as AdminCategoryIdRoute from "@/app/admin/[categoryId]/page.info";
import * as ApiAuthAuth0Route from "@/app/api/auth/[auth0]/route.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const CategoryId = makeRoute(
  "/[categoryId]",
  {
    ...defaultInfo,
    ...CategoryIdRoute.Route
  }
);
export const CategoryIdStateStateId = makeRoute(
  "/[categoryId]/state/[stateId]",
  {
    ...defaultInfo,
    ...CategoryIdStateStateIdRoute.Route
  }
);
export const CategoryIdStateStateIdHikingId = makeRoute(
  "/[categoryId]/state/[stateId]/[hikingId]",
  {
    ...defaultInfo,
    ...CategoryIdStateStateIdHikingIdRoute.Route
  }
);
export const Admin = makeRoute(
  "/admin",
  {
    ...defaultInfo,
    ...AdminRoute.Route
  }
);
export const AdminCategoryId = makeRoute(
  "/admin/[categoryId]",
  {
    ...defaultInfo,
    ...AdminCategoryIdRoute.Route
  }
);
export const ApiAuthAuth0 = makeRoute(
  "/api/auth/[auth0]",
  {
    ...defaultInfo,
    ...ApiAuthAuth0Route.Route
  }
);

