// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as CategoryIdRoute from "@/app/[categoryId]/page.info";
import * as ApiAuthAuth0Route from "@/app/api/auth/[auth0]/route.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const CategoryId = makeRoute(
  "/[categoryId]",
  {
    ...defaultInfo,
    ...CategoryIdRoute.Route
  }
);
export const ApiAuthAuth0 = makeRoute(
  "/api/auth/[auth0]",
  {
    ...defaultInfo,
    ...ApiAuthAuth0Route.Route
  }
);

